import { ASSETS_DIRECTORY_NAME, SVG_FILE_NAMES } from "./constants.js";
import type { CasinoContext } from "./types.js";
import { escapeMarkdown } from "./utils/escape-xml.js";
import { formatCurrency, formatNumber, toDisplayName } from "./utils/format.js";

const FENCE = "```";

/** Relative asset path used inside the generated README. Always POSIX style. */
function assetPath(fileName: string): string {
  return `./${ASSETS_DIRECTORY_NAME}/${fileName}`;
}

/** Builds the complete, fully centred, entirely irresponsible README. */
export function generateReadme(context: CasinoContext): string {
  const { projectName, stats, slot } = context;
  const safeName = escapeMarkdown(projectName);
  const displayName = escapeMarkdown(toDisplayName(projectName));
  const valuation = formatCurrency(stats.valuation);

  const lines = [
    `<div align="center">`,
    ``,
    `<img src="${assetPath(SVG_FILE_NAMES.casino)}" alt="${displayName} Code Casino" width="100%">`,
    ``,
    `<img src="${assetPath(SVG_FILE_NAMES.marquee)}" alt="Casino marquee lights" width="100%">`,
    ``,
    `<img src="${assetPath(SVG_FILE_NAMES.slots)}" alt="Slot machine showing ${escapeMarkdown(slot.symbol)}" width="900">`,
    ``,
    `# 🎰 ${safeName} 🎰`,
    ``,
    `### WHERE CODE MEETS FINANCIAL IRRESPONSIBILITY`,
    ``,
    `**${escapeMarkdown(slot.title)}** — ${escapeMarkdown(slot.subtitle)}`,
    ``,
    `<img src="${assetPath(SVG_FILE_NAMES.stats)}" alt="High roller statistics" width="900">`,
    ``,
    `---`,
    ``,
    `## 💰 REPOSITORY VALUATION`,
    ``,
    `# ${valuation}`,
    ``,
    `**Revenue:** \`$0\`  `,
    `**Bugs:** \`Premium\`  `,
    `**Production readiness:** \`Allegedly\`  `,
    `**Technical debt:** \`Compounding daily\`  `,
    `**Vibe multiplier:** \`×${formatNumber(stats.bugMultiplier)}\`  `,
    `**Investor confidence:** \`${stats.investorConfidence}%\`  `,
    `**Test coverage:** \`Trust me\``,
    ``,
    `---`,
    ``,
    `## 🎲 INSTALLATION`,
    ``,
    `${FENCE}bash`,
    `npm install`,
    `${FENCE}`,
    ``,
    `## 🃏 USAGE`,
    ``,
    `${FENCE}bash`,
    `npm run dev`,
    `${FENCE}`,
    ``,
    `---`,
    ``,
    `<img src="${assetPath(SVG_FILE_NAMES.jackpot)}" alt="Mega jackpot worth ${valuation}" width="100%">`,
    ``,
    `### THE HOUSE ALWAYS WINS`,
    ``,
    `YOUR CODE MAY BE BROKEN, BUT YOUR README IS RICH`,
    ``,
    `Generated by **README Casino**`,
    ``,
    `</div>`,
    ``,
  ];

  return lines.join("\n");
}
